### ISSUE TITLE
Colour configuration 

### ISSUE THREAD

**Issue by eddyekofo94** [numToStr/FTerm.nvim#23]
I see there's no way to modify colours. I got a [PR](https://github.com/eddyekofo94/gruvbox-flat.nvim/issues/4) concerning the colours not showing on FTerm. my attempt to fix it locally seems to not be working.

 ``` lua
 local filetype = vim.api.nvim_buf_get_option(0, "filetype")

  -- File/buffer specific settings
  if filetype == "FTerm"  then
    colors.black = "#fff"
    colors.bg2 = "#fff"
  end
```
I think the problem might be stemming from [this](https://github.com/eddyekofo94/gruvbox-flat.nvim/blob/521d9234d1c8c3a0e9dc782a8f2e5776483856b0/lua/gruvbox/colors.lua#L47). Any help or suggestions would be appreciated. Thanks

**Comment by numToStr** [comment]
Hey, I am aware of this issue. This is the same issue I faced when I was using [gruvbox-material](https://github.com/sainnhe/gruvbox-material). 

The reason is for this issue is that terminal colors are not set properly or overlap with the background which makes it kinda invisible.

I am maintaining my own Lua fork of `gruvbox-material` which has fixes for this issue.
https://github.com/numToStr/gruvbox-material/blob/dbafc4f38a7a00cbfd90fead1f3cf8ba6b3a3ae6/lua/gruvbox-material/definitions.lua#L1572

This is how it looks with the patches.
![image](https://user-images.githubusercontent.com/24727447/120058568-73b0d580-c069-11eb-91fc-0cb1da805c16.png)

Hope this helps :)

**Comment by eddyekofo94** [comment]
Thanks, now I see where I was erring, thanks :)
