### ISSUE TITLE
Launch terminal with command

### ISSUE THREAD

**Issue by chmln** [numToStr/FTerm.nvim#6]
It would be great to have the ability to pass a command to a floating terminal.
I would use this to launch `lazygit` with a single keybind.

**Comment by numToStr** [comment]
This feature was also in my mind. But I think I might need to implement multiple terminals instances first as currently It only supports only one terminal instance.

**Comment by EpsilonKu** [comment]
So I found function "chansend()" which can send argument to terminal (https://neovim.io/doc/user/channel.html). I guess it will help you.

**Comment by numToStr** [comment]
As it turns out this was fairly easy to implement, I just need to allow the run command to be customizable. You just need to need to use the underlying terminal instance to make this work. Just switch to the `multi` branch to test it out give your initial feedback. If you have anything else on your mind do let me know.

And also Sorry for the delay :)

### Example
```lua
local term = require("FTerm.terminal")

-- Opening bashtop
local bashtop = term:new()

bashtop:setup({cmd = "bashtop"})

function _G.__fterm_bashtop()
    bashtop:toggle()
end

-- Opening gitui
local gitui = term:new()

gitui:setup({cmd = "gitui"})

function _G.__fterm_gitui()
    gitui:toggle()
end
```

### In Action

https://user-images.githubusercontent.com/24727447/113911583-c2738900-97f7-11eb-8a01-22918b333572.mp4

> Just ignore the broken highlights in `gitui`

**Comment by EpsilonKu** [comment]
That's good. What about to make symbols (like % in Floaterm) to send file name.

**Comment by numToStr** [comment]
I am not sure about the vim character like '%', '$'. But you can use the lua API like `vim.api.nvim_get_current_buf()` which I think is same as '%'
